### ISSUE TITLE
Issues with text/bg opacity?

### ISSUE THREAD

**Issue by captenmasin** [mertasan/tailwindcss-variables#2] opened 2021-04-28 21:58 UTC
### Versions:
- Package Version: 1.0.3
- Tailwindcss Version: 2.1.1

### Question:
I'm not sure if this would even be possible with how Tailwind as a whole is setup to work, but basically when using this plugin it will create a CSS variable like so 

```css
--colors-primary: #7868e6;
```

Which is great, but when using in conjunction with anything related to opacity it doesn't respect that at all

For example
```html
<div class="bg-primary bg-opacity-50"></div>
```
Doesn't have a background opacity of 50

Of course this could (theoretically) be fixed in userland by setting the variable in tailwindconfig.js like so

```js
colors: {
	primary: {
		DEFAULT: 'var(--colors-primary), var(--tw-bg-opacity)'
	},
}
```

But then this won't text into account the `text-opacity` classes

Has anyone managed to figure this out?

**Comment by mertasan** [comment] 2021-04-29 00:28
@captenmasin please upgrade the plugin to `v1.1.0`

73a0596edf197506dc975847c5770baafdb7509a

```js
// tailwind.config.js

const colorVariable = require('@mertasan/tailwindcss-variables/colorVariable')

module.exports = {
  theme: {
    colors: {
      primary: colorVariable('--colors-primary'),
      secondary: colorVariable('var(--colors-secondary)'), // or
      gray: 'var(--colors-gray)', // or default usage
    },
    variables: {
      DEFAULT: {
        colors: {
          primary: '#ffffff',
          secondary: '#000000',
          gray: '#6B7280'
        },
      },
      },
    },
  },
  plugins: [
    require('@mertasan/tailwindcss-variables')
  ]
}
```

**output:**

```css
:root {
   --colors-primary: #ffffff;
   --colors-secondary: #000000;
   --colors-gray: #6B7280
}

.text-primary {
  --tw-text-opacity: 1;
  color: rgba(var(--colors-primary), var(--tw-text-opacity))
}

.bg-secondary {
  --tw-bg-opacity: 1;
  background-color: rgba(var(--colors-secondary), var(--tw-bg-opacity))
}

.bg-gray {
  background-color: var(--colors-gray)
}
```

**Comment by mertasan** [comment] 2021-04-29 00:31
https://github.com/mertasan/tailwindcss-variables/blob/73a0596edf197506dc975847c5770baafdb7509a/__tests__/color-variable-helper.test.js#L37-L63

**Comment by captenmasin** [comment] 2021-04-29 08:28
It worked!
Thank you I appreciate the help

One thing I noticed is variables must be set like so
```
const primary = '120, 104, 230'
const secondary = '120, 104, 230'
const tertiary = '228, 251, 255'
```

As wrapping them in rgb() like `rgb(228, 251, 255)` would result in the CSS being read as:
```
.bg-tertiary {
    --tw-bg-opacity: 1;
	background-color: rgba(rgb(228, 251, 255), 1);
}
```
Which, of course, isn't valid

**Comment by captenmasin** [comment] 2021-04-29 08:29
Hex values in the variables also don't work as will output
```
rgba(#e4fbff, 1)
```

Which also isn't valid

**Comment by mertasan** [comment] 2021-04-29 09:56
I have new ideas on this. The new version will be released within a few hours 👍

**Comment by mertasan** [comment] 2021-04-29 11:47
```javascript
plugins: [
  require('@mertasan/tailwindcss-variables'){
    colorVariables: true
  }
]
````

**Example**

```javascript
// tailwind.config.js

const colorVariable = require('@mertasan/tailwindcss-variables/colorVariable')

module.exports = {
  theme: {
    colors: {
      primary: colorVariable('--colors-primary'),
      secondary: colorVariable('var(--colors-secondary)'), // or
      gray: 'var(--colors-gray)', // or default usage
    },
    variables: {
      DEFAULT: {
        colors: {
          primary: '#ff0',
          secondary: '#000000',
          gray: '#6B7280'
        },
      },
      },
    },
  },
  plugins: [
    require('@mertasan/tailwindcss-variables'){
      colorVariables: true
    }
  ]
}
```

**Output:**

```css
:root {
  --colors-primary: #ff0;
  --colors-secondary: #000000;
  --colors-gray: #6B7280;
  --colors-primary-rgb: 255,255,0;
  --colors-secondary-rgb: 0,0,0;
  --colors-gray-rgb: 107,114,128
}

.text-primary {
  --tw-text-opacity: 1;
  color: rgba(var(--colors-primary-rgb), var(--tw-text-opacity))
}

.bg-secondary {
  --tw-bg-opacity: 1;
  background-color: rgba(var(--colors-secondary-rgb), var(--tw-bg-opacity))
}

.bg-gray {
  background-color: var(--colors-gray)
}
```

**Closed** 2021-04-29 15:43 UTC
Labels: question, solved

**Comment by irg1008** [comment] 2021-07-11 02:05
Sorry to type after the issue has been closed, but this is not working with twin.macro, do you have any idea why? Thanks

**Comment by mertasan** [comment] 2021-07-11 02:14
@irg1008 I'm testing. I hope it's something I can fix.

**Comment by mertasan** [comment] 2021-07-11 02:16
@irg1008 can you give me a sample `tailwind.config.js` file?

**Comment by irg1008** [comment] 2021-07-11 02:47
I know why is happening, Twin.Macro does not support your plugin and similars... :(

**Comment by mertasan** [comment] 2021-07-11 04:26
@irg1008 

- Do not include variables in the extended configs.
- Use the names of the variables as follows.

```js
module.exports = {
    theme: {
        extend: {
            ...
        },
        variables: {
            DEFAULT: {
               ...
            }
        }
    }
}
```

I used this example: https://github.com/ben-rogerson/twin.examples/tree/master/next-stitches-typescript

Example configuration:

```js
const colorVariable = require("@mertasan/tailwindcss-variables/colorVariable");

module.exports = {
    darkMode: 'media',
    theme: {
        extend: {
            colors: {
                primary: colorVariable('--colors-bg-red', true),
                secondary: colorVariable('--colors-bg-blue', true),
            },
        },
        variables: {
            DEFAULT: {
                colors: {
                    bg: {
                        red: '#b81313',
                        blue: '#0c61be'
                    },
                },
            }
        },
        darkVariables: {
            DEFAULT: {
                colors: {
                    bg: {
                        red: '#b81313',
                        blue: '#ac1515'
                    },
                },
            }
        }
    },
    plugins: [
        require('@mertasan/tailwindcss-variables')({
            colorVariables: true,
            forceRGB: true,
        })
    ],
}
```


```tsx
// pages/index.tsx

import React from 'react'
import tw, { styled } from 'twin.macro'
import { Logo, Button } from '../components'

const Container = styled.div({
  ...tw`flex flex-col items-center justify-center h-screen`,
  variants: {
    hasBackground: {
      true: tw`bg-gradient-to-b from-primary to-secondary`,
    },
  },
})

const ButtonBox = tw.div`flex flex-col justify-center h-full gap-y-5`

const IndexPage = () => (
  <Container hasBackground>
    <ButtonBox>
      <Button variant="primary">Submit</Button>
      <Button variant="secondary">Cancel</Button>
      <Button isSmall>Close</Button>
    </ButtonBox>
    <Logo />
  </Container>
)

export default IndexPage
```
```tsx
// components/Button.tsx

import tw, { styled, theme } from 'twin.macro'

const Button = styled.button({
  // Add classes with the tw import and spread syntax
  ...tw`px-8 py-2 rounded transform duration-75 outline-none focus:outline-none`,

  // Use the variant grouping feature to add variants to multiple classes
  ...tw`hocus:(scale-105 text-yellow-300)`, // hocus = hover + focus

  // The theme import grabs values from your tailwind.config.js
  color: theme`colors.white`,

  // Use variants/compoundVariants to conditionally style your components
  // https://stitches.dev/docs/variants
  variants: {
    // Style based on props, eg: <div variant="primary" />
    variant: {
      primary: tw`
        bg-primary text-white border-2 border-white bg-opacity-100
        focus:(ring-2 ring-yellow-400)
      `,
      secondary: tw`
        bg-secondary border-2 border-white bg-opacity-100
        focus:(ring-2 ring-purple-400)

        // Use short css to combine tailwind classes with regular css
        box-shadow[0 0.1em 0 0 rgba(0, 0, 0, 0.25)]
      `,
    },
    // Boolean props can be styled too, eg: <div isSmall /> / <div isSmall={false} />
    isSmall: { true: tw`text-sm`, false: tw`text-lg` },
  },
})

export default Button
```

I don't know why but `--tw-bg-opacity` was not added for some reason. This causes the background color to not show. You can also solve this by adding `bg-opacity-100`

![screenshot 65](https://user-images.githubusercontent.com/13007665/125182728-29e70d80-e219-11eb-9377-a51193ac8e10.png)

**Comment by irg1008** [comment] 2021-07-11 12:01
It works! But as you said we have to add bg-opacity-100, I think this could be solved with and if statment on the --tw-bg-opacity value. Passing 1 in case this variable is undefined.

**Comment by mertasan** [comment] 2021-07-11 13:30
This was suggested by @adamwathan. https://github.com/adamwathan/tailwind-css-variable-text-opacity-demo

I also added new tests. 93f79747613e8619d28b54ef03f2f6eeac8a5736

I've never used a twin.macro

I'm also not sure if this works as it should for the twin.macro. However, I will investigate. If this is an issue that needs to be resolved and the issue is not related to my package, I may need to create a PR for the twin as well.
@irg1008

**Comment by irg1008** [comment] 2021-07-12 00:16
The suggested method does not work either with twin.macro. Shame because it lacks that feature to be s great library

**Comment by irg1008** [comment] 2021-07-12 00:46
Okay so this method worked:
"This was suggested by @adamwathan. https://github.com/adamwathan/tailwind-css-variable-text-opacity-demo"

It only worked when combining it with the bg-opacity-100 that you suggested previously.
To avoid setting it up in every component, we can set it in the body tag and all components will inherit it as default.

Thanks for the help! Hope the team as Twin.Macro thinks about adding support for awesome plugins as yours!
